apiVersion: v1
kind: ConfigMap
metadata:
  name: nitter-config
  namespace: default
data:
  nitter.conf: |
    [Server]
    address = "0.0.0.0"
    port = 8080
    https = false
    httpMaxConnections = 100
    staticDir = "./public"
    title = "nitter"
    hostname = "nitter.midagedev.com"

    [Cache]
    listMinutes = 240
    rssMinutes = 10
    redisHost = ""
    redisPort = 6379
    redisPassword = ""
    redisConnections = 20
    redisMaxConnections = 30

    [Config]
    hmacKey = "secretkey"
    base64Media = false
    enableRSS = true
    enableDebug = false
    proxy = ""
    proxyAuth = ""
    tokenCount = 10

    [Preferences]
    theme = "Nitter"
    replaceTwitter = "nitter.midagedev.com"
    replaceYouTube = ""
    replaceReddit = ""
    replaceInstagram = ""
    proxyVideos = true
    hlsPlayback = false
    infiniteScroll = false
